// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskAPIDataAccess;

namespace TaskAPIDataAccess.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    [Migration("20220222070259_AuthorEntityAndData")]
    partial class AuthorEntityAndData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TaskAPI.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Bimsara Vibuthi"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Chamara Madhusanka"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Dinesh Indunil"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Ravidu Hasmitha"
                        });
                });

            modelBuilder.Entity("TaskAPI.Models.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Due")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Created = new DateTime(2022, 2, 22, 12, 32, 58, 482, DateTimeKind.Local).AddTicks(7344),
                            Description = "Get some text books for school",
                            Due = new DateTime(2022, 2, 27, 12, 32, 58, 484, DateTimeKind.Local).AddTicks(2898),
                            Status = 0,
                            Title = "Get books for school - DB"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            Created = new DateTime(2022, 2, 22, 12, 32, 58, 484, DateTimeKind.Local).AddTicks(4359),
                            Description = "Get vegitables for the week",
                            Due = new DateTime(2022, 2, 24, 12, 32, 58, 484, DateTimeKind.Local).AddTicks(4367),
                            Status = 0,
                            Title = "Get vegitables - DB"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            Created = new DateTime(2022, 2, 22, 12, 32, 58, 484, DateTimeKind.Local).AddTicks(4380),
                            Description = "Water the all plants quickly",
                            Due = new DateTime(2022, 2, 23, 12, 32, 58, 484, DateTimeKind.Local).AddTicks(4383),
                            Status = 0,
                            Title = "Water the plants"
                        });
                });

            modelBuilder.Entity("TaskAPI.Models.Todo", b =>
                {
                    b.HasOne("TaskAPI.Models.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });
#pragma warning restore 612, 618
        }
    }
}
